on:
    push:
        branches:
            -   main
name: 🚀 Deploy Blog
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Installing Node Modules Project
      run:  npm ci
    

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{secrets.server}}
        username: ${{secrets.username}}
        password: ${{secrets.password }}
        server-dir: /trade-blog.vitalskillsda.com/

 
