on:
  push:
      branches:
          -   main
name: 🚀 Deploy App on Push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
        # hello

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v3.1.1
      with:
        # ftp-server: ftpes://ftp.<REDACTED>.com
        # ftp-username: <REDACTED>
        ftp-server: staging.trademindshub.com/staging.trademindshub.com/
        ftp-username: makarios
        ftp-password: Xcode@200
        # protocol: ftps
        # log-level: verbose
        # local-dir:  ./dist/
        # server-dir: /staging.trademindshub.com/